require("plugins")
require("keybindings")
require("options")
require("nvim-tree-config")
require("lualine-config")
require("bufferline-config")
require("treesitter-config")
require("autopairs-config")
require("whichkey-config")
require("telescope-config")
require("colorizer-config")
require("gitsigns-config")
require("coc-config")
require("dashboard-config")
require("blankline-config")
require("formatter-config")

vim.cmd("colorscheme gruvbox8")
