#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# window
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# mouse
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# borders
yabai -m config window_border                off
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xffdfbf8e
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               2
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   2

# Spaces
yabai -m space 1 --label 1
yabai -m space 2 --label 2
yabai -m space 3 --label 3
yabai -m space 4 --label 4
yabai -m space 5 --label 5
yabai -m space 6 --label 6
yabai -m space 7 --label 7
yabai -m space 8 --label 8
yabai -m space 9 --label 9
yabai -m space 10 --label 10

# specific space settings
yabai -m config --space 2  layout        stack

yabai -m config --space 5  layout        float
yabai -m config --space 10 layout        float

# Screen 1
# Browsers
yabai -m rule --add app="Google Chrome" space=1
yabai -m rule --add app="Safari"        space=1

# IDE's
yabai -m rule --add app="PhpStorm" space=2
yabai -m rule --add app="GoLand" space=2

yabai -m rule --add app="Sublime Text"  space=3
yabai -m rule --add app="TablePlus"  space=4


# Screen 2
# Terminal
yabai -m rule --add app="alacritty" space=6
yabai -m rule --add app="iTerm" space=6
yabai -m rule --add app="kitty" space=6

yabai -m rule --add app="Slack"  space=7
yabai -m rule --add app="GitHub Desktop"  space=8
yabai -m rule --add app="Spark"  space=9


# ignore apps

# regex that matches JetBrains apps
ignoreApps='^(System Preferences|Karabiner-Elements|Karabiner-EventViewer|Finder|Alfred Preferences|Disk Utility|System Information|Activity Monitor|Path Finder|Docker Desktop|App Store)$'

# float all JetBrains apps
yabai -m rule --add app="${ignoreApps}" manage=off

# yabai -m rule --add app="^System Preferences$" manage=off



# Some Goland settings, in case you are using it. float Goland Preference panes
yabai -m rule --add app="PhpStorm" manage=off
yabai -m rule --add app="PhpStorm" title=".*\[(.*)\].*" manage=on

yabai -m rule --add app="GoLand" manage=off
yabai -m rule --add app="GoLand" title=".*\[(.*)\].*" manage=on

# status bar stuff
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# if using multple displays, add an additional rule for "display_changed" event
yabai -m signal --add event=display_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# add these rules to auto-update the "windows" widget
yabai -m signal --add event=window_focused \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=window_destroyed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=window_created \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"


# external bar
yabai -m config external_bar all:26:0

echo "yabai configuration loaded.."
